### ISSUE TITLE
k-LMS doesnt produce an image, it appears to be working but then at the end there is just noise

### ISSUE THREAD

**Issue by G-force78** [nousr/robo-diffusion#1]
Using automatic1111 collab with a VAE

https://imgur.com/a/zC5O4rL

Settings:
Sampler: LMS Karras, CFG scale: 10, Seed: 734318933, Size: 448x832, Model hash: 41fef4bd, Model: robo-diffusion-v1, Denoising strength: 0.9, Mask blur: 4

**Comment by nousr** [comment]
KLMS is known to not work well with dreambooth finetunes
 
https://wandb.ai/psuraj/dreambooth/reports/Dreambooth-training-analysis--VmlldzoyNzk0NDc3
